// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlndmoxsnccurcfpxeai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsbmRtb3hzbmNjdXJjZnB4ZWFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2ODA0OTAsImV4cCI6MjA2OTI1NjQ5MH0.V6CMWCb0_CNPNt08DZHQepeK2S4eShYxHOgrwjAAy88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});